# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoverLetterGenerator.ui',
# licensing of 'CoverLetterGenerator.ui' applies.
#
# Created: Mon Jul 29 18:31:44 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 623)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(51, 51, 51)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(102, 255, 255)")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(102, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(102, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(102, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.letterInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letterInput.sizePolicy().hasHeightForWidth())
        self.letterInput.setSizePolicy(sizePolicy)
        self.letterInput.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.letterInput.setObjectName("letterInput")
        self.verticalLayout.addWidget(self.letterInput)
        self.editTemplateButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editTemplateButton.sizePolicy().hasHeightForWidth())
        self.editTemplateButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Copperplate")
        font.setPointSize(15)
        font.setWeight(50)
        font.setBold(False)
        self.editTemplateButton.setFont(font)
        self.editTemplateButton.setAcceptDrops(False)
        self.editTemplateButton.setAutoFillBackground(False)
        self.editTemplateButton.setStyleSheet("background-color: rgba(95, 255, 255, 189)")
        self.editTemplateButton.setObjectName("editTemplateButton")
        self.verticalLayout.addWidget(self.editTemplateButton)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateButton.sizePolicy().hasHeightForWidth())
        self.updateButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Copperplate")
        font.setPointSize(15)
        font.setWeight(50)
        font.setBold(False)
        self.updateButton.setFont(font)
        self.updateButton.setAcceptDrops(False)
        self.updateButton.setAutoFillBackground(False)
        self.updateButton.setStyleSheet("background-color: rgb(102, 204, 255)")
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout.addWidget(self.updateButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.variableBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variableBox.sizePolicy().hasHeightForWidth())
        self.variableBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.variableBox.setFont(font)
        self.variableBox.setAutoFillBackground(False)
        self.variableBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgba(76, 192, 190, 153);")
        self.variableBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.variableBox.setObjectName("variableBox")
        self.horizontalLayout_2.addWidget(self.variableBox)
        self.variableEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variableEdit.sizePolicy().hasHeightForWidth())
        self.variableEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.variableEdit.setFont(font)
        self.variableEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.variableEdit.setObjectName("variableEdit")
        self.horizontalLayout_2.addWidget(self.variableEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateButton.sizePolicy().hasHeightForWidth())
        self.generateButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Copperplate")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.generateButton.setFont(font)
        self.generateButton.setAcceptDrops(False)
        self.generateButton.setAutoFillBackground(False)
        self.generateButton.setStyleSheet("background-color: rgb(102, 255, 102)")
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("color: rgb(91, 194, 255)")
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Template", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Type/edit your letter below. Include variables by typing them in double arrows without spaces like this:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "<<Employer>>", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "The variables will be included in the box below the letter.", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "To save your letter, click \"Save Template Letter.\"", None, -1))
        self.editTemplateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Edit Template letter", None, -1))
        self.updateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save Template Letter", None, -1))
        self.generateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Letter", None, -1))

